// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('busqueda', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('busqueda', async function() {
    await driver.get("https://cursosdedesarrollo.com/")
    await driver.findElement(By.name("s")).sendKeys("testing")
    await driver.findElement(By.css(".search-submit")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Search results for: testing")
  })
})
